function xddot = Xddot(theta,thetadot,u,xdot)
%Xddot
%    XDDOT = Xddot(THETA,THETADOT,U,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Sep-2025 12:34:36

t2 = cos(theta);
t3 = sin(theta);
xddot = ((u.*1.0e+2-xdot.*1.0e+1+t2.*t3.*1.47e+2+t3.*thetadot.^2.*6.0).*(-1.0./5.0))./(t2.^2.*3.0-1.4e+1);
end
