function B_mat = BMat_zero
%BMAT_ZERO
%    B_MAT = BMAT_ZERO

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Nov-2019 13:55:40

B_mat = reshape([0.0,-1.668738547843186,0.0,-2.415137157251242e1,2.901430611957418e-2,0.0,0.0,0.0],[4,2]);
