function vdot = Vdot(omega,phi,phidot,u1)
%VDOT
%    VDOT = VDOT(OMEGA,PHI,PHIDOT,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Nov-2019 13:55:40

t2 = cos(phi);
t3 = sin(phi);
t4 = phidot.^2;
t5 = t2.^2;
vdot = (u1.*1.4244e10-t2.*t3.*2.664038713e10+t3.*t4.*4.48678878e8+t2.*u1.*6.2999e9+omega.^2.*t3.*4.48678878e8-t3.*t4.*t5.*2.71840685e8)./(t5.*2.71840685e9-1.5029442648e10);
